### ISSUE TITLE
Tipp: IE 7 support

### ISSUE THREAD

**Issue by IngwiePhoenix** [sunflowerdeath/webfonts-generator#1]
I just discovered this tool and am pretty baffled why it isnt known like it should be. The potential of this tool is huge, so I am adding it to my project.

In order to support IE 7, since this is, for now, the lowest target I want to choose, one can use the following trick:

http://stackoverflow.com/a/15262501/2423150

Since you use templates, this shouldn't be too big to implement, and neat int he long-run.

Thanks for making this tool, I am going to work on implementing it with [WebPack](https://github.com/webpack/webpack) :)

**Comment by sunflowerdeath** [comment]
According to http://www.w3schools.com/browsers/browsers_explorer.asp only 0.1% users have IE7, so I don't want to support it.
