### ISSUE TITLE
Cant give absolute paths in options.cssFontsPath

### ISSUE THREAD

**Issue by b11n** [sunflowerdeath/webfonts-generator#10]
When I give a full http/https url for **cssFontsPath**, its being changed to a single slash.I have css inline and generated font is on a cdn hence cannot give a relative path.

**Comment by sunflowerdeath** [comment]
Problem was that value used as a path, and not as URL.
I fixed it, and also I decided to rename this option from `cssFontsPath` to `cssFontsUrl`.
`cssFontsPath` is not removed yet, but now it shows deprecation message.

**Comment by b11n** [comment]
Thanks . Working perfectly !
