### ISSUE TITLE
Font with bad resolution

### ISSUE THREAD

**Issue by OrencioRodolfo** [sunflowerdeath/webfonts-generator#11]
For some SVG files the generated font presents icons with low resolution and I can't notice why.
The following attachment is one of these situations.

Looking at its source code, everything looks similar to other SVG icons that are successfully generated.

Also, if you generate a font for the following icon using fontastic, it is successfully generated.

[calendar.zip](https://github.com/sunflowerdeath/webfonts-generator/files/257478/calendar.zip)

**Comment by loick** [comment]
Hi, it's similar to many font generator you can find I think. There are some recommendation of exporting it into svg of 500 x 500 minimum. Yours is in 30x30

**Comment by OrencioRodolfo** [comment]
@loick thank you for the feedback.

Will take it into consideration
