### ISSUE TITLE
need to update HTMLBars

### ISSUE THREAD

**Issue by ehariprasad** [sunflowerdeath/webfonts-generator#17]
Hi, 

We are using this awesome package to generate fonts in our ember app. Now we are trying to upgrade from 2.7.0 to 2.9.0, during the process we are getting error in scss.hbs with variable '@key'. In ember 2.8 they have [disallowed using @ in hbs templates](https://github.com/emberjs/ember.js/pull/13913). So we need to update htmlbars version to 4.0.5 so that we can use |key value| set in templates.

I have seen [pull request](https://github.com/sunflowerdeath/webfonts-generator/pull/15) , on using which its working fine locally. But to make it working on production i need to fork your 'broccoli-webfont' and 'ember-cli-webfont'. Can you update htmlbar package in your package.json so that i don't need to do fork those libraries.

Thanks,
Hari

**Comment by moimael** [comment]
#15 is merged.
