### ISSUE TITLE
Upgrade to svgicons2svgfont 2.0.2

### ISSUE THREAD

**Issue by nfroidure** [sunflowerdeath/webfonts-generator#3]
https://github.com/nfroidure/svgicons2svgfont

There are breaking changes and new features (ligatures, several codepoints for the same icon).

You may want to use the same logic than the CLI util and gulp-iconfont to parse unicode and icon names in the file names https://github.com/nfroidure/svgicons2svgfont/blob/master/src/metadata.js

I'm available if you have any question / require any help on switching to the new API.

**Comment by sunflowerdeath** [comment]
Thx for issue, I have updated to new api, though I don't support ligatures and several codepoints yet.
