### ISSUE TITLE
Please support woff2

### ISSUE THREAD

**Issue by honi** [sunflowerdeath/webfonts-generator#5]
I believe you can use [ttf2woff2](https://www.npmjs.com/package/ttf2woff2) and add it to the generators config in generateFonts.js. Is there anything else to keep in mind? Let me know if you want me to send a PR.

**Comment by IngwiePhoenix** [comment]
I'd like this as well.

**Comment by mysterycommand** [comment]
+1

**Comment by oligriffiths** [comment]
+1

**Comment by moimael** [comment]
See #16

**Comment by evilebottnawi** [comment]
We can use mu solution https://github.com/itgalaxy/webfont

**Comment by moimael** [comment]
#16 is merged.

**Comment by jeerbl** [comment]
Hello,

Is it released yet?

Thanks,
Jerome

**Comment by moimael** [comment]
No not yet, I don't have permission to publish on npm, I need to contact the original author for this

**Comment by sunflowerdeath** [comment]
I will publish soon

**Comment by scott-thrillist** [comment]
@sunflowerdeath Conan O'Brien himself said he needs woff2 support in npm land :)

**Comment by sunflowerdeath** [comment]
https://www.npmjs.com/package/webfonts-generator
