### ISSUE TITLE
rendering issue 

### ISSUE THREAD

**Issue by matthieucolas** [sunflowerdeath/webfonts-generator#52]
Hi, i've been experiencing some rendering trouble with the generated font glyphs, i get this : 
![image](https://user-images.githubusercontent.com/17146187/42336400-e096e06e-8083-11e8-999c-f2bee72aafa3.png)
instead of this :
![image](https://user-images.githubusercontent.com/17146187/42336439-fae166ec-8083-11e8-8290-6cd153e02d86.png)

 see the difference ? does it rings a bell to anyone ? Am i missing something ? For the records, the second image have been generated with an all integrated tool, like icomoon or other.

**Comment by ritz078** [comment]
See https://github.com/sunflowerdeath/webfonts-generator/issues/50 . use svg with resolution >= 1000px.

**Comment by matthieucolas** [comment]
thanks ! it worked fine !
